"""add review_queue for human-in-the-loop exceptions

Revision ID: 09f850c1a96f
Revises: c2af9e570573
Create Date: 2026-09-07 18:45:09.156433

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09f850c1a96f"
down_revision: str | Sequence[str] | None = "c2af9e570573"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_queue",
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("citation", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resume_token", sa.String(length=64), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("assigned_to", sa.String(length=128), nullable=True),
        sa.Column("resolution", sa.String(length=24), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "reason IN ('solver_not_optimal','solver_infeasible','low_extraction_confidence','threshold_near_miss','rate_unavailable','unknown_field_label','jurisdiction_ambiguous','deadline_imminent')",
            name="ck_review_reason",
        ),
        sa.CheckConstraint(
            "resolution IS NULL OR resolution IN ('approved','rejected','corrected','deferred')",
            name="ck_review_resolution",
        ),
        sa.CheckConstraint(
            "severity IN ('low','normal','high','blocking')", name="ck_review_severity"
        ),
        sa.CheckConstraint(
            "state <> 'resolved' OR (resolution IS NOT NULL AND resolved_at IS NOT NULL)",
            name="ck_resolved_rows_are_explained",
        ),
        sa.CheckConstraint("state IN ('open','claimed','resolved')", name="ck_review_state"),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.claim_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("review_id"),
        sa.UniqueConstraint("resume_token"),
    )
    op.create_index("ix_review_queue_claim", "review_queue", ["claim_id"], unique=False)
    op.create_index(
        "ix_review_queue_open", "review_queue", ["tenant_id", "state", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_queue_open", table_name="review_queue")
    op.drop_index("ix_review_queue_claim", table_name="review_queue")
    op.drop_table("review_queue")
    # ### end Alembic commands ###
