"""baseline: dual-jurisdiction claim state machine

Revision ID: c2af9e570573
Revises:
Create Date: 2026-09-07 17:59:30.877694

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c2af9e570573"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("default_jurisdiction", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("default_jurisdiction IN ('us','ksa')", name="ck_tenant_jurisdiction"),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "claims",
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("lane", sa.String(length=32), nullable=False),
        sa.Column("drawback_type", sa.String(length=40), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("filing_deadline", sa.Date(), nullable=False),
        sa.Column("absolute_bar_date", sa.Date(), nullable=True),
        sa.Column("total_refund", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(jurisdiction = 'us' AND currency = 'USD') OR (jurisdiction = 'ksa' AND currency = 'SAR')",
            name="ck_claim_currency_matches_jurisdiction",
        ),
        sa.CheckConstraint(
            "(jurisdiction = 'us' AND lane IN ('drawback','post_summary_correction','fta_retroactive')) OR (jurisdiction = 'ksa' AND lane IN ('gcc_reexport_drawback','ksa_origin_refund'))",
            name="ck_claim_lane_matches_jurisdiction",
        ),
        sa.CheckConstraint(
            "jurisdiction = 'us' OR drawback_type NOT IN ('unused_substitution','manufacturing_substitution')",
            name="ck_no_substitution_outside_us",
        ),
        sa.CheckConstraint("jurisdiction IN ('us','ksa')", name="ck_claim_jurisdiction"),
        sa.CheckConstraint(
            "state IN ('intake','extracting','extracted','classifying','classified','matching','matched','quantified','analyst_review','approved','packaged','handed_off','filed','paid','rejected','expired')",
            name="ck_claim_state",
        ),
        sa.CheckConstraint("period_end >= period_start", name="ck_claim_period_ordered"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("claim_id"),
    )
    op.create_index(
        "ix_claims_deadline", "claims", ["jurisdiction", "filing_deadline"], unique=False
    )
    op.create_index("ix_claims_tenant_state", "claims", ["tenant_id", "state"], unique=False)
    op.create_table(
        "documents",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("language IN ('en','ar','mixed')", name="ck_document_language"),
        sa.CheckConstraint("char_length(sha256) = 64", name="ck_document_sha256_length"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("document_id"),
        sa.UniqueConstraint("tenant_id", "sha256", name="uq_document_tenant_sha256"),
    )
    op.create_index("ix_documents_tenant_kind", "documents", ["tenant_id", "kind"], unique=False)
    op.create_table(
        "entry_lines",
        sa.Column("line_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("declaration_number", sa.String(length=64), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("import_date", sa.Date(), nullable=False),
        sa.Column("declaration_date", sa.Date(), nullable=False),
        sa.Column("duty_payment_date", sa.Date(), nullable=True),
        sa.Column("port_of_entry", sa.String(length=16), nullable=False),
        sa.Column("country_of_origin", sa.String(length=2), nullable=False),
        sa.Column("hts_code", sa.String(length=12), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=16), nullable=False),
        sa.Column("entered_value", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("duty_paid", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("mpf_paid", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("hmf_paid", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("section_301_duty", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("other_duty", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("vat_paid", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("excise_paid", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("quantity_designated", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "jurisdiction <> 'ksa' OR duty_payment_date IS NOT NULL",
            name="ck_ksa_requires_payment_date",
        ),
        sa.CheckConstraint("jurisdiction IN ('us','ksa')", name="ck_entry_jurisdiction"),
        sa.CheckConstraint("quantity > 0", name="ck_entry_quantity_positive"),
        sa.CheckConstraint("quantity_designated <= quantity", name="ck_entry_not_over_designated"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("line_id"),
        sa.UniqueConstraint(
            "tenant_id", "declaration_number", "line_number", name="uq_entry_line_declaration"
        ),
    )
    op.create_index(
        "ix_entry_lines_clock",
        "entry_lines",
        ["tenant_id", "jurisdiction", "duty_payment_date"],
        unique=False,
    )
    op.create_index(
        "ix_entry_lines_tenant_hts", "entry_lines", ["tenant_id", "hts_code"], unique=False
    )
    op.create_table(
        "export_lines",
        sa.Column("line_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), nullable=False),
        sa.Column("reference", sa.String(length=128), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("export_date", sa.Date(), nullable=False),
        sa.Column("destination_country", sa.String(length=2), nullable=True),
        sa.Column("is_destruction", sa.Boolean(), nullable=False),
        sa.Column("hts_code", sa.String(length=12), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=16), nullable=False),
        sa.Column("declared_value", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("quantity_claimed", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("linked_import_declaration", sa.String(length=64), nullable=True),
        sa.Column("consignment_id", sa.String(length=128), nullable=True),
        sa.Column("is_partial_shipment", sa.Boolean(), nullable=False),
        sa.Column("unused_and_unaltered", sa.Boolean(), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "jurisdiction <> 'ksa' OR linked_import_declaration IS NOT NULL",
            name="ck_ksa_requires_declaration_link",
        ),
        sa.CheckConstraint("jurisdiction IN ('us','ksa')", name="ck_export_jurisdiction"),
        sa.CheckConstraint(
            "is_destruction OR destination_country IS NOT NULL",
            name="ck_export_destination_or_destruction",
        ),
        sa.CheckConstraint("quantity_claimed <= quantity", name="ck_export_not_over_claimed"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("line_id"),
        sa.UniqueConstraint("tenant_id", "reference", "line_number", name="uq_export_line_ref"),
    )
    op.create_index(
        "ix_export_lines_linkage",
        "export_lines",
        ["tenant_id", "linked_import_declaration"],
        unique=False,
    )
    op.create_table(
        "claim_transitions",
        sa.Column("transition_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("from_state", sa.String(length=24), nullable=True),
        sa.Column("to_state", sa.String(length=24), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.claim_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("transition_id"),
    )
    op.create_index(
        "ix_claim_transitions_claim", "claim_transitions", ["claim_id", "occurred_at"], unique=False
    )
    op.create_table(
        "refund_lines",
        sa.Column("refund_line_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("import_line_id", sa.UUID(), nullable=False),
        sa.Column("export_line_id", sa.UUID(), nullable=False),
        sa.Column("theory", sa.String(length=32), nullable=False),
        sa.Column("substitution_key", sa.String(length=8), nullable=True),
        sa.Column("linked_import_declaration", sa.String(length=64), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("duty_component", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("mpf_component", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("hmf_component", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("refund_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("days_clock_start_to_export", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "theory <> 'declaration_linkage' OR linked_import_declaration IS NOT NULL",
            name="ck_linkage_has_declaration",
        ),
        sa.CheckConstraint(
            "theory <> 'hts_substitution' OR substitution_key IS NOT NULL",
            name="ck_substitution_has_key",
        ),
        sa.CheckConstraint(
            "theory IN ('direct_identity','hts_substitution','declaration_linkage')",
            name="ck_refund_theory",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_refund_quantity_positive"),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.claim_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["export_line_id"], ["export_lines.line_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["import_line_id"], ["entry_lines.line_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("refund_line_id"),
    )
    op.create_index("ix_refund_lines_claim", "refund_lines", ["claim_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_refund_lines_claim", table_name="refund_lines")
    op.drop_table("refund_lines")
    op.drop_index("ix_claim_transitions_claim", table_name="claim_transitions")
    op.drop_table("claim_transitions")
    op.drop_index("ix_export_lines_linkage", table_name="export_lines")
    op.drop_table("export_lines")
    op.drop_index("ix_entry_lines_tenant_hts", table_name="entry_lines")
    op.drop_index("ix_entry_lines_clock", table_name="entry_lines")
    op.drop_table("entry_lines")
    op.drop_index("ix_documents_tenant_kind", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_claims_tenant_state", table_name="claims")
    op.drop_index("ix_claims_deadline", table_name="claims")
    op.drop_table("claims")
    op.drop_table("tenants")
    # ### end Alembic commands ###
