"""add tariff corpus with pgvector for classification search

Revision ID: d41e3e45b5f1
Revises: 09f850c1a96f
Create Date: 2026-09-07 21:54:21.944813

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d41e3e45b5f1"
down_revision: str | Sequence[str] | None = "09f850c1a96f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classification_queries",
        sa.Column("query_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("jurisdiction", sa.String(length=8), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("revision", sa.String(length=32), nullable=True),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("method", sa.String(length=24), nullable=False),
        sa.Column(
            "asked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("method IN ('vector','lexical','hybrid')", name="ck_query_method"),
        sa.PrimaryKeyConstraint("query_id"),
    )
    op.create_index(
        "ix_classification_queries_tenant",
        "classification_queries",
        ["tenant_id", "asked_at"],
        unique=False,
    )
    op.create_table(
        "tariff_lines",
        sa.Column("tariff_line_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("heading", sa.String(length=4), nullable=False),
        sa.Column("hs6", sa.String(length=6), nullable=False),
        sa.Column("description_en", sa.Text(), nullable=False),
        sa.Column("description_ar", sa.Text(), nullable=True),
        sa.Column("unit_of_quantity", sa.String(length=24), nullable=True),
        sa.Column("duty_rate_general", sa.String(length=64), nullable=True),
        sa.Column("duty_rate_special", sa.String(length=255), nullable=True),
        sa.Column("duty_rate_column2", sa.String(length=64), nullable=True),
        sa.Column("ad_valorem_rate", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("revision", sa.String(length=32), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code ~ '^[0-9]{6,12}$'", name="ck_tariff_code_digits"),
        sa.CheckConstraint(
            "jurisdiction <> 'us' OR length(description_en) > 0", name="ck_us_lines_have_english"
        ),
        sa.CheckConstraint("jurisdiction IN ('us','ksa')", name="ck_tariff_jurisdiction"),
        sa.CheckConstraint("source IN ('usitc_hts','zatca_tariff')", name="ck_tariff_source"),
        sa.CheckConstraint("left(code, 4) = heading", name="ck_tariff_heading_matches_code"),
        sa.CheckConstraint("left(code, 6) = hs6", name="ck_tariff_hs6_matches_code"),
        sa.PrimaryKeyConstraint("tariff_line_id"),
        sa.UniqueConstraint("jurisdiction", "source", "code", "revision", name="uq_tariff_line"),
    )
    op.create_index(
        "ix_tariff_lines_desc_en_trgm",
        "tariff_lines",
        ["description_en"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description_en": "gin_trgm_ops"},
    )
    op.create_index("ix_tariff_lines_hs6", "tariff_lines", ["hs6"], unique=False)
    op.create_index(
        "ix_tariff_lines_lookup", "tariff_lines", ["jurisdiction", "code"], unique=False
    )
    op.create_table(
        "tariff_rulings",
        sa.Column("ruling_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("ruling_number", sa.String(length=48), nullable=False),
        sa.Column("ruling_date", sa.Date(), nullable=False),
        sa.Column("classified_code", sa.String(length=12), nullable=False),
        sa.Column("hs6", sa.String(length=6), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("superseded_by", sa.String(length=48), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("jurisdiction IN ('us','ksa')", name="ck_ruling_jurisdiction"),
        sa.CheckConstraint("source IN ('cbp_cross','zatca_ruling')", name="ck_ruling_source"),
        sa.PrimaryKeyConstraint("ruling_id"),
        sa.UniqueConstraint("source", "ruling_number", name="uq_ruling_number"),
    )
    op.create_index(
        "ix_rulings_code", "tariff_rulings", ["jurisdiction", "classified_code"], unique=False
    )
    op.create_index("ix_rulings_hs6", "tariff_rulings", ["hs6"], unique=False)
    # ### end Alembic commands ###

    # Vector similarity indexes. HNSW rather than IVFFlat: IVFFlat needs a populated
    # table to train its lists, and the corpus is ingested incrementally, so an index
    # built now against an empty table would be badly tuned for the eventual data.
    op.execute(
        "CREATE INDEX ix_tariff_lines_embedding ON tariff_lines "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_tariff_rulings_embedding ON tariff_rulings "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # Trigram index over ruling text, for the lexical half of hybrid search.
    op.execute(
        "CREATE INDEX ix_rulings_text_trgm ON tariff_rulings "
        "USING gin ((subject || ' ' || body) gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_rulings_text_trgm")
    op.execute("DROP INDEX IF EXISTS ix_tariff_rulings_embedding")
    op.execute("DROP INDEX IF EXISTS ix_tariff_lines_embedding")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rulings_hs6", table_name="tariff_rulings")
    op.drop_index("ix_rulings_code", table_name="tariff_rulings")
    op.drop_table("tariff_rulings")
    op.drop_index("ix_tariff_lines_lookup", table_name="tariff_lines")
    op.drop_index("ix_tariff_lines_hs6", table_name="tariff_lines")
    op.drop_index(
        "ix_tariff_lines_desc_en_trgm",
        table_name="tariff_lines",
        postgresql_using="gin",
        postgresql_ops={"description_en": "gin_trgm_ops"},
    )
    op.drop_table("tariff_lines")
    op.drop_index("ix_classification_queries_tenant", table_name="classification_queries")
    op.drop_table("classification_queries")
    # ### end Alembic commands ###
